name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Task
        run: |
          echo "This task runs every 5 minutes"
