name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      access-key-id: "123456-77777-999999"
      secret-key-id: "12345-99999-00000"
    steps:
      # - name: 'Az CLI login'
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: 'Run az commands'
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show
    - name: Checkout
      uses: actions/checkout@v4

    - name: call shell and pass input params 
      run: |
        chmod +x "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"
        "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"

          
