name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r "${GITHUB_WORKSPACE}/scripts/requirements.txt"
      
      - name: check cerbot version
        run: |
          certbot --version
      
      - name: create dirs for certbot
        run: |
          mkdir -p /tmp/cert-logs /tmp/cert-config /tmp/cert-work

      - name: deploy certbot
        run: |
          certbot certonly \
          --logs-dir /path/to/your/logdir \
          --work-dir /path/to/your/workdir \
          --config-dir /path/to/your/configdir \
          --register-unsafely-without-email \
          -d example.com

      # - name: run certbot commands
        
      # - name: Run shell script
      #   run: |
      #     chmod +x scripts/script.sh
      #     ./scripts/script.sh
