name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          chmod +x scripts/script.sh
          ./scripts/script.sh
