name: Verify Schedule Job

on:
  schedule:
    - cron: '*/1 * * * *' 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: green
        options:
          - blue
          - green
          - ctest

jobs:
  new-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ github.event_name == 'schedule' && fromJson('["blue", "green"]') || fromJson(format('["{0}"]', inputs.env)) }}
    steps:
      - name: Print Variables
        env:
          environment: ${{ matrix.environment }}
          product_name: ${{ format('app-bs-{0}', matrix.environment) }}
        run: |
          echo "Environment: $environment"
          echo "Product Name: $product_name"
