name: Verify Schedule Job

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: green
        options:
          - blue
          - green
          - ctest
      product_name:
        type: string
        default: "default-product"
        description: "Specify the product name manually for manual trigger"

env:
  product: "bs-abc"

jobs:
  new-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ github.event_name == 'schedule' && fromJson('["blue", "green"]') || fromJson(format('["{0}"]', inputs.env)) }}
    steps:
      - name: Set Environment Variables
        id: set-vars
        env:
          environment: ${{ matrix.environment }}
          product_name: ${{ github.event_name == 'workflow_dispatch' && format('{0}-test', inputs.product_name) || format('app-bs-{0}', matrix.environment) }}
          rg: ${{ github.event_name == 'workflow_dispatch' && format('{0}-test', inputs.product_name) || format('{0}-rg-{1}', env.product, matrix.environment) }}
        run: |
          echo "Environment: $environment"
          echo "Product Name: $product_name"
          echo "Resource Group: $rg"
          # Expose these variables for subsequent steps
          echo "RG=$rg" >> $GITHUB_ENV
          echo "PRODUCT_NAME=$product_name" >> $GITHUB_ENV

      - name: Use RG in Another Step
        run: |
          echo "Using RG variable in this step:"
          echo "Resource Group: $RG"
          echo "Product Name: $PRODUCT_NAME"
