name: Run Azure CLI Login with OpenID Connect
on: [push]

permissions:
  id-token: write 
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v5

    - name: python version installed is 
      run: |
        python --version

    - name: run script 
      run: |
        chmod +x "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"
        "${GITHUB_WORKSPACE}/scripts/certbot/test.sh " 

#    - name: Azure CLI Login
#      uses: azure/login@v2
#      with:
#        client-id: ${{ secrets.AZURE_CLIENT_ID }}
#        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#  
#    - name: Azure CLI script
#      uses: azure/cli@v2
#      with:
#        azcliversion: latest
#        inlineScript: |
#          az account show
