name: Run Azure CLI Login with OpenID Connect

on:
  workflow_dispatch: 
    inputs: 
      is-blue: 
        description: 'blue-deployment' 
        required: true
        type: boolean
        default: true 
      sub:
        description: 'Subscription for Azure'
        required: true
        default: '29876-6666-0000'
      tenant-id:
        description: 'Tenant for Azure'
        required: true
        default: '123-5444-333'

permissions:
  id-token: write 
      
jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      default-env: "blue"
      default-domain: "xyz.com"
      RG: "hello"
      RP: "HI"
      dns-zone: "${{ env.default-domain }}:/sub/${{ github.event.inputs.sub }}/rg/${{ env.RG }}/providers/ms/dns-zone/${{ env.default-domain }}"
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set domain based on env 
        id: set-domain
        run: | 
          if [ "${{ github.event.inputs.is-blue }}" = true ]; then 
            echo "env=${{ env.default-env }}" >> $GITHUB_ENV 
            echo "domain=${{ env.default-domain }}" >> $GITHUB_ENV
          else 
            echo "default-env=green" >> $GITHUB_ENV 
            echo "default-domain=abc.com" >> $GITHUB_ENV
          fi

      - name: Set dns-zone
        id: set-dns-zone
        run: | 
          echo "dns_zone=${{ env.default-domain }}:/sub/${{ github.event.inputs.sub }}/rg/${{ env.RG }}/providers/ms/dns-zone/${{ env.default-domain }}" >> $GITHUB_ENV

      - name: Print vars 
        run: |
          echo "env is : ${{ env.default-env }}" 
          echo "domain is : ${{ env.default-domain }}"
          echo "dns-zone is : ${{ env.dns_zone }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Python version installed
        run: |
          python --version

      - name: Create config file and cat it 
        run: | 
          cat <<EOF > certbot-config.ini
dns_azure_use_workload_identity_credentials = true
dns_azure_environment = "AzurePublicCloud"
dns_azure_zone1 = "${{ env.dns_zone }}"
EOF
          cat certbot-config.ini

      - name: Run script 
        run: | 
          chmod +x "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"
          cat <<EOF > env_vars.json
{
  "default_env": "${{ env.env }}",
  "default_domain": "${{ env.domain }}",
  "RG": "${{ env.RG }}",
  "RP": "${{ env.RP }}"
}
EOF
          "${GITHUB_WORKSPACE}/scripts/certbot/test.sh" env_vars.json certbot-config.ini

      - name: Install dependencies
        run: pip install -r "${GITHUB_WORKSPACE}/scripts/requirements.txt"

      - name: Certbot version
        run: certbot --version

      - name: Azure CLI version
        run: az --version
