name: Run Azure CLI Login with OpenID Connect
on:
  workflow_dispatch: 
    inputs: 
      env: 
        description: 'Environment' 
        required: true 
        default: 'blue' 
      domain: 
        description: 'Domain' 
        required: true 
        default: 'xyz.com'

permissions:
  id-token: write 
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set domain based on env 
      run: |
        if [ "$env" != "blue"]; then
          echo "domain=abc.com" >> $GITHUB_ENV
    - name: print vars
      run: |
        echo "env is : $env"
        echo "domain is : $domain"

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: python version installed is 
      run: |
        python --version

    - name: run script
      run: |
        chmod +x "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"
        "${GITHUB_WORKSPACE}/scripts/certbot/test.sh" 


#    - name: run script
#      env:
#        GITHUB_WORKSPACE: ${{ github.workspace }}
#      run: |
#        chmod +x "${GITHUB_WORKSPACE}/scripts/certbot/test.sh"
#        "${GITHUB_WORKSPACE}/scripts/certbot/test.sh" 
#
    - name: install dependencies
      run: pip install -r "${GITHUB_WORKSPACE}/scripts/requirements.txt"

    - name: certbot
      run:
        certbot --version

    - name: az cli
      run:
        az --version


#    - name: Azure CLI Login
#      uses: azure/login@v2
#      with:
#        client-id: ${{ secrets.AZURE_CLIENT_ID }}
#        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#  
#    - name: Azure CLI script
#      uses: azure/cli@v2
#      with:
#        azcliversion: latest
#        inlineScript: |
#          az account show
